CREATE TABLE IF NOT EXISTS weekly_performance_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  snapshot_date DATE NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  dept_code VARCHAR(20) DEFAULT NULL,
  year VARCHAR(10) DEFAULT NULL,
  section VARCHAR(10) DEFAULT NULL,
  degree VARCHAR(50) DEFAULT NULL,
  leetcode_total_problems INT NOT NULL DEFAULT 0,
  leetcode_contests INT NOT NULL DEFAULT 0,
  gfg_total_problems INT NOT NULL DEFAULT 0,
  gfg_contests INT NOT NULL DEFAULT 0,
  codechef_total_problems INT NOT NULL DEFAULT 0,
  codechef_contests INT NOT NULL DEFAULT 0,
  hackerrank_total_badges INT NOT NULL DEFAULT 0,
  total_problems INT NOT NULL DEFAULT 0,
  total_contests INT NOT NULL DEFAULT 0,
  active_leetcode TINYINT(1) NOT NULL DEFAULT 0,
  active_gfg TINYINT(1) NOT NULL DEFAULT 0,
  active_codechef TINYINT(1) NOT NULL DEFAULT 0,
  active_hackerrank TINYINT(1) NOT NULL DEFAULT 0,
  captured_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_week_student (week_start, student_id),
  INDEX idx_week_filters (week_start, dept_code, year, section, degree)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
